service: my-movies-d5a83

provider:
  name: google
  runtime: nodejs
  project: my-movies-d5a83
  credentials: ~/.gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  movieWebhook:
    handler: movieWebhook
    events:
      - http: path